version: '3'

services:
  web:
    build: .
    command: gunicorn Pesquisa_Core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./Static:/root/pesquisa_django_full/static
      - ./Media:/root/pesquisa_django_full/media
    depends_on:
      - web
