# Generated by Django 5.0.4 on 2024-04-08 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0002_campanha_campanha_imagem'),
        ('perguntas_respostas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('resposta_texto', models.TextField()),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanhas.campanha')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas_respostas.pergunta')),
            ],
        ),
    ]
