# Generated by Django 5.0.4 on 2024-04-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='campanha_imagem',
            field=models.ImageField(blank=True, upload_to='imagens_campanha/'),
        ),
    ]
