# Generated by Django 5.0.4 on 2024-04-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_campanha_campanha_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='campanha_fundo',
            field=models.ImageField(blank=True, upload_to='imagens_campanha_fundo/'),
        ),
    ]
